INSERT INTO roles (nombre) VALUES ('DOCENTE'), ('EVALUADOR'), ('ADMINISTRADOR');
INSERT INTO `carrera`(`id`, `coordinacion`, `director`, `nombre`, `periodo`) VALUES ('1', 'VERONICA PAULINA CHIMBO CORONEL', 'DIRECTORA DE TECNOLOGÍA SUPERIOR EN BIG DATA', 'CARRERA TECNOLOGÍA SUPERIOR EN BIGDATA', '2024-2025'); 

INSERT INTO `carrera`(`id`, `coordinacion`, `director`, `nombre`, `periodo`) VALUES ('2', 'VICTORIA MARILYN SALAZAR PIÑA', 'DIRECTORA DE ENTRENAMIENTO DEPORTIVO CON EQUIVALENTE A TECNOLOGIA SUPERIOR', 'CARRERA ENTRENAMIENTO DEPORTIVO CON EQUIVALENTE A TECNOLOGIA SUPERIOR', '2024-2025');

INSERT INTO `carrera`(`id`, `coordinacion`, `director`, `nombre`, `periodo`) VALUES ('3', 'CRUZ GERMANIA DIAZ HERRERA', 'DIRECTORA DE TÉCNICO EN SEGURIDAD PENITENCIARIA', 'CARRERA TÉCNICO EN SEGURIDAD PENITENCIARIA', '2024-2025'); 

INSERT INTO `carrera`(`id`, `coordinacion`, `director`, `nombre`, `periodo`) VALUES ('4', 'JAIME GEOVANY LOJA BUESTÁN', 'DIRECTOR DE TECNOLOGÍA SUPERIOR EN PRODUCCIÓN Y REALIZACIÓN AUDIOVISUAL', 'CARRERA TECNOLOGÍA SUPERIOR EN PRODUCCIÓN Y REALIZACIÓN AUDIOVISUAL', '2024-2025'); 

INSERT INTO `carrera`(`id`, `coordinacion`, `director`, `nombre`, `periodo`) VALUES ('5', 'MARIA VERONICA SEGARRA VANEGAS', 'DIRECTORA DE TECNOLOGÍA SUPERIOR EN DESARROLLO DE SOFTWARE', 'CARRERA TECNOLOGÍA SUPERIOR EN DESARROLLO DE SOFTWARE', '2024-2025'); 
